server:
  port: 8080
spring:
  datasource:
    username: truong
    password: comebackt0me.
    url: jdbc:mysql://localhost/e_commerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect