server:
  port: 8080
spring:
  datasource:
    username: truong
    password: comebackt0me.
    url: jdbc:mysql://localhost/e_commerce?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: truong01.bp@gmail.com
    password: comebackt0me.
    protocol: smtp
    properties: { "mail.smtp.starttls.enable" : "true", "mail.smtp.auth" : "true"}
